### ISSUE TITLE
Remove final newline based on file type?

### ISSUE THREAD

**Issue by mhulse** [DoCode/vscode-remove-final-newlines#4]
Any chance this can, or could, work with an array of file extensions? I would like to remove all newlines from end of specific file types.

Thanks!

**Comment by DoCode** [comment]
Thanks @mhulse for your feedback!

Yes, I think it's possible. I look at this ASAP.
What's your opinion about the defaults?

**Comment by mhulse** [comment]
Oh, no rush on my behalf!

Thinking out loud here:

- If the array of file types not filled-in, then the extension will work on all file types? (thus, not introducing any backwards-incompatible changes)
- If file types added to options array, then the extension only works on provided extensions?

**Comment by DoCode** [comment]
Ok, then we should implement this setting, e.g. for JSON, JS and TS file extensions:
```json
{
  "files.removeFinalNewlines.fileTypes": ["json", "js", "ts"]
}
```

**Comment by mhulse** [comment]
That looks awesome! I think this feature would really be a nice addition to this extension. I might have some time this weekend to possibly do a PR. I'll keep you posted. 👍

**Comment by mhulse** [comment]
Wondering, would it make sense to have a blacklist/whitelist type of thing?

So, whitelist would be extensions this plugin would work on, and blacklist would be extensions this plugin would ignore.

This might give people more flexibility?

Of course, I maybe be overthinking things here.

**Comment by DoCode** [comment]
Yes, nice!
I think the same last night.
What about includes/excludes like
```json
{
  "files.removeFinalNewlines.fileTypes.include": ["json", "js", "ts"],
  "files.removeFinalNewlines.fileTypes.exclude": ["md", "mdown", "log"
}

**Comment by mhulse** [comment]
I think that's a winner.

Was also wondering, would regex support be overkill? like `md*`, for example? Or, `.*.hb` maybe? I'm not sure how complicated it would be to implement, but I'm reminded of something like EditorConfig regex (for example):

```ini
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = false
indent_size = 4
indent_style = tab

[*.py]
indent_style = space

[*.{ini,json,rb,yml,sh,bash}]
indent_size = 2
indent_style = space

[.*rc]
indent_size = 2
indent_style = space

[{gemfile*,rakefile,vagrantfile}]
indent_size = 2
indent_style = space

[*.bat]
end_of_line = crlf

[cname]
insert_final_newline = false
```

Or, [`node-glob`](https://github.com/isaacs/node-glob#glob-primer).

**Comment by DoCode** [comment]
No, I think it's no overkill, eventually an additional feature!?
After we have the include/exclude implementation, it's no big deal for globbing or regex support.

**Comment by DoCode** [comment]
@mhulse sorry for the silence...
Should we respect or implement like [this here](https://github.com/microsoft/vscode/issues/26707)?

**Comment by mhulse** [comment]
Sorry for being afk. I have actually been using IntelliJ as my primary code tool since I last filed this issue ... Apologies for not helping. :(

Anyway, Looks like you got it solved! Nice work. :)

**Comment by DoCode** [comment]
No problem. Thanks Michael!
